server:
  port: 10003

spring: 
    # 数据源部分
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/bookstore_springboot
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.zq.bookstore.book.pojo# 注意：对应实体类的路径
  
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql